<a href="https://colab.research.google.com/github/VictorMorais777/Disciplina-de-Inteligencia-Artificial/blob/main/DataScience_JoaoVictorSilvaMorais_6B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Exercicios de NumPy 1

In [ ]:
import numpy as np

array = np.random.randint(10, 101, 50)

print(array)

[58 78 43 20 98 28 26 57 85 10 59 95 85 88 85 64 68 43 91 70 93 97 47 37
 71 46 90 84 97 58 12 20 45 93 26 22 51 20 27 87 37 58 45 34 64 20 24 58
 42 52]


 Exercıcios de NumPy 2

In [ ]:
import numpy as np

array = np.arange(1, 17)
matriz = array.reshape(4, 4)
matriz[3, :]

print(matriz[3, :])

[13 14 15 16]


 Exercıcios de NumPy 3

In [ ]:
import numpy as np

array = np.zeros(15)
array[4:10] = 1

print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


 Exercıcios de NumPy 4

In [ ]:
import numpy as np
from statistics import mode

array = np.random.randint(1, 101, 100)
mediana = np.median(array)
moda = mode(array)

print(mediana)
print(moda)

53.0
90


 Exercıcios de NumPy 5

In [ ]:
import numpy as np

array = np.random.randint(1, 101, 20)
array[array % 3 == 0] = -3

print(array)



[97 -3 -3 -3 88 -3 58 28 49 -3 -3 86 19 29  7 80 -3 83  7 40]


 Exercıcios de NumPy 6

In [ ]:
import numpy as np

matriz = np.random.random((5, 5))
somacolunas = np.sum(matriz, axis=0)

print(somacolunas)

[1.97310487 2.5591437  1.94904226 2.13180551 2.56227016]


Exercıcios de NumPy 7

In [ ]:
import numpy as np

array1 = np.random.rand(20)
array2 = np.random.rand(20)
correlacao1 = np.corrcoef(array1, array2)
correlacao = correlacao1[0, 1]

print(correlacao)

-0.23325637077145528


Exercıcios de NumPy 8

In [ ]:
import numpy as np

matriz = np.random.randint(1, 101, (3, 3))
elevado = matriz ** 2

print(matriz)
print(elevado)


[[ 67  10  14]
 [ 30  66  51]
 [100   6  83]]
[[ 4489   100   196]
 [  900  4356  2601]
 [10000    36  6889]]


Exercıcios de NumPy 9

In [ ]:
import numpy as np

array = np.random.random(10)
minimo = np.min(array)
maximo = np.max(array)
normalizado = (array - minimo) / (maximo - minimo)

print(normalizado)

[0.89816421 0.91185381 0.52431284 1.         0.37604764 0.
 0.54453856 0.6522075  0.78481577 0.85729883]


Exercıcios de NumPy 10

In [ ]:
import numpy as np

matriz = np.eye(6)
matriz[np.diag_indices(6)] = [1, 2, 3, 4, 5, 6]

print(matriz)

[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


Exercıcios de NumPy 11

In [ ]:
import numpy as np
from statistics import mode

array = np.random.randint(1, 101, 100)
mais_repete = mode(array)

print(mais_repete)


92


Exercıcios de NumPy 12

In [ ]:
import numpy as np

matriz = np.eye(4)
matriz[np.diag_indices(4)] = 7

print(matriz)

[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


Exercıcios de NumPy 13

In [ ]:
import numpy as np

array = np.arange(2, 22, 2)
soma = np.cumsum(array)

print(soma)

[  2   6  12  20  30  42  56  72  90 110]


Exercıcios de NumPy 14

In [ ]:
import numpy as np

array1 = np.random.randint(1, 101, 10)
array2 = np.random.randint(1, 101, 10)
diferenca = array1 - array2
media = np.mean(diferenca)

print(media)


-24.1


Exercıcios de NumPy 15

In [ ]:
import numpy as np

array = np.random.randint(1, 101, 20)
array[array > 50] = 50

print(array)


[31 50 21  1 50 50 50 50 50 11 50 50 18 50 50 50 50 50 47 50]


Exercıcios de NumPy 16

In [ ]:
import numpy as np

array = np.arange(1, 13)
matriz = array.reshape(3,4)

print(matriz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Exercıcios de NumPy 17

In [ ]:
import numpy as np

matriz = np.random.randint(1, 101, (4, 4))
posicoes = np.arange(1, 17).reshape(4, 4)
resultado = matriz * posicoes

print(matriz)
print(resultado)

[[ 71  14  20  30]
 [ 32  95  25  75]
 [ 68 100  65  83]
 [ 44   3  65  78]]
[[  71   28   60  120]
 [ 160  570  175  600]
 [ 612 1000  715  996]
 [ 572   42  975 1248]]


Exercıcios de NumPy 18

In [ ]:
import numpy as np

array = np.random.randint(1, 101, 10)
array[array % 5 == 0] = 0

print(array)

[44 99 43 31 51 77  0 19 36 61]


Exercıcios de NumPy 19

In [ ]:
import numpy as np

array1 = np.random.randint(1, 101, 20)
array2 = np.random.randint(1, 101, 20)
produto = np.dot(array1, array2)
norma1 = np.linalg.norm(array1)
norma2 = np.linalg.norm(array2)
coseno = produto / (norma1 * norma2)
angulo = np.arccos(coseno)
angulo = np.degrees(angulo)

print(angulo)



43.490935123953896


Exercıcios de NumPy 20

In [ ]:
import numpy as np

matriz = np.random.randint(1, 101,(4, 4))
minimo = np.min(matriz, axis=1)

print(matriz)
print(minimo)

[[ 4 54 21 32]
 [65 19 10 25]
 [45 81 23 45]
 [42 14 29 25]]
[ 4 10 23 14]


Exercıcios de SciPy 1

In [ ]:
import numpy as np
from scipy import integrate

def f(x):
    return x**2 * np.sin(x)

resultado, erro = integrate.quad(f, 0, np.pi)

print(resultado)
print(erro)

5.869604401089359
6.516569951530559e-14


Exercıcios de SciPy 2

In [ ]:
from scipy.integrate import solve_ivp

def equacao(x, y):
    return x - y

resultado = solve_ivp(equacao, [0, 10], [1])

print(resultado)

  message: The solver successfully reached the end of the integration interval.
  success: True
   status: 0
        t: [ 0.000e+00  8.707e-02  8.991e-01  1.669e+00  2.600e+00
             3.790e+00  5.341e+00  7.433e+00  1.000e+01]
        y: [[ 1.000e+00  9.203e-01  7.132e-01  1.046e+00  1.749e+00
              2.836e+00  4.351e+00  6.435e+00  9.000e+00]]
      sol: None
 t_events: None
 y_events: None
     nfev: 50
     njev: 0
      nlu: 0


Exercıcios de SciPy 3

In [ ]:
from scipy import optimize

def f(x):
    return x**4 - 3*x**3 + 2

for tentativa in [-5, -2, -1, 0, 1, 2, 3, 4, 5]:
    raiz = optimize.root(f, tentativa)
    print(tentativa, raiz.x)


-5 [2.91963957]
-2 [1.]
-1 [1.]
0 [0.]
1 [1.]
2 [1.]
3 [2.91963957]
4 [2.91963957]
5 [2.91963957]


Exercıcios de SciPy 4

In [ ]:
from scipy import optimize

def f(x):
    return -x**2 + 4*x + 1

def negativa(x):
    return -f(x)

resultado = optimize.minimize(negativa, 1)

print(resultado.x)
print(f(resultado.x))

[1.99999998]
[5.]


Exercıcios de SciPy 5

In [ ]:
from scipy.fft import fft
import numpy as np

t = np.linspace(0, 1, 500)
sinal = np.sin(2 * np.pi * t) + 0.5 * np.sin(4 * np.pi * t)
frequencias = fft(sinal)

print(frequencias)


[ 4.18415302e-15-0.00000000e+00j  1.57129054e+00-2.50075366e+02j
  1.56073553e+00-1.24192849e+02j -1.84544966e-02+9.78925495e-01j
 -1.51223694e-02+6.01573266e-01j -1.40594189e-02+4.47377963e-01j
 -1.35622414e-02+3.59579183e-01j -1.32848761e-02+3.01855737e-01j
 -1.31129698e-02+2.60654499e-01j -1.29985705e-02+2.29620125e-01j
 -1.29183953e-02+2.05332014e-01j -1.28599366e-02+1.85769314e-01j
 -1.28159542e-02+1.69654649e-01j -1.27820080e-02+1.56137963e-01j
 -1.27552466e-02+1.44630128e-01j -1.27337678e-02+1.34709192e-01j
 -1.27162621e-02+1.26064585e-01j -1.27018034e-02+1.18462400e-01j
 -1.26897214e-02+1.11722972e-01j -1.26795208e-02+1.05705926e-01j
 -1.26708293e-02+1.00299942e-01j -1.26633627e-02+9.54155684e-02j
 -1.26569007e-02+9.09800815e-02j -1.26512704e-02+8.69337337e-02j
 -1.26463347e-02+8.32269718e-02j -1.26419838e-02+7.98183443e-02j
 -1.26381286e-02+7.66729046e-02j -1.26346965e-02+7.37609799e-02j
 -1.26316277e-02+7.10572093e-02j -1.26288726e-02+6.85397858e-02j
 -1.26263898e-02+6.618985

Exercıcios de SciPy 6

In [ ]:
import numpy as np
from scipy.linalg import inv

matriz = np.random.randint(1, 101, (5, 5))
inversa = inv(matriz)

print(matriz)
print(inversa)

[[36 96 98 59 49]
 [47 68 90 24 27]
 [86 22 51 49 19]
 [65 99 12 25 37]
 [72 76 38  4 99]]
[[-1.22268781e-02  7.40110672e-03  8.88121991e-03  4.22311643e-03
   7.50390512e-04]
 [ 2.20027370e-05  4.71354988e-03 -8.03195845e-03  1.18341491e-02
  -4.17778069e-03]
 [-1.45359640e-03  1.43520120e-02 -1.05475578e-03 -8.29753014e-03
   1.08796718e-04]
 [ 1.96119021e-02 -2.48061173e-02  9.63229075e-03 -6.20155507e-04
  -4.55844251e-03]
 [ 8.64093002e-03 -1.35076915e-02 -2.77448832e-04 -8.94619141e-03
   1.29048759e-02]]


Exercıcios de SciPy 7

In [ ]:
import numpy as np
from scipy import interpolate

x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 2, 3, 5, 4])

f_interpolada = interpolate.interp1d(x, y, kind='cubic')

x_novo = np.array([0.5, 1.5, 2.5, 3.5])

y_novo = f_interpolada(x_novo)

print(y_novo)

[1.34375 2.40625 4.03125 5.21875]


Exercıcios de SciPy 8

In [ ]:
import numpy as np
from scipy.linalg import solve

A = np.array([[3, 2],
             [1, 4]])

B = np.array([5, 6])

resultado = solve(A, B)

print(resultado)

[0.8 1.3]


Exercıcios de SciPy 9

In [ ]:
import numpy as np
from scipy.optimize import curve_fit

def curva(x, a, b, c):
    return a*x**2 + b*x + c

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 7, 8])

parametros, _ = curve_fit(curva, x, y)

print(parametros)

[-0.07142857  1.92857143  0.2       ]


Exercıcios de SciPy 10

In [ ]:
import numpy as np
from scipy import integrate

def f(x, y):
    return x*y + x**2

resultado, erro = integrate.dblquad(
     f,
     0, 2,
     lambda x: 0,
     lambda x: 1
)

print(resultado)
print(erro)

1.6666666666666665
1.850371707708594e-14


Exercıcios de SciPy 11

In [ ]:
from scipy.linalg import eig
import numpy as np

matriz = np.random.randint(1, 101, (4, 4))
autovalores, autovetores = eig(matriz)

print(matriz)
print(autovalores)
print(autovetores)

[[43 29 40 38]
 [58 24 76 44]
 [64 43  1 31]
 [82 93 29 99]]
[201.6764028 +0.j  16.59450839+0.j  -1.1620243 +0.j -50.10888689+0.j]
[[ 0.34459896  0.13171212  0.22600139 -0.20795877]
 [ 0.43957865  0.49442435 -0.73950102 -0.67294905]
 [ 0.3221658   0.31426    -0.26195166  0.56986853]
 [ 0.76435029 -0.79964813  0.57744519  0.42325239]]


Exercıcios de SciPy 12

In [ ]:
import numpy as np
from scipy import optimize

def f(x):
    return np.exp(x) - x**2

raiz = optimize.root(f, 1)

print(raiz.x)

[-0.70346742]


Exercıcios de SciPy 13

In [ ]:
import numpy as np
from scipy.linalg import det

matriz = np.random.randint(-10, 11, (6, 6))
determinate = det(matriz)

print(matriz)
print(determinate)

[[10  9 -1  9  0  9]
 [ 7  7 -8 -9  6 -9]
 [ 5 -3 -2  6 10 -3]
 [ 4 10  9  2  7  3]
 [ 0 -1  6 -8  0  0]
 [-8  6 -9 10 -4 -2]]
-146885.0000000003


Exercıcios de SciPy 14

In [ ]:
import numpy as np
from scipy.optimize import minimize

def f(x):
    return (x[0] - 2) **2 + (x[1] - 3) ** 2

solucao = minimize(f, [1, 1])

print(solucao.x)
print(solucao.fun)

[1.99999999 2.99999999]
1.7057803420206568e-16


Exercıcios de SciPy 15

In [ ]:
import numpy as np
from scipy.fft import ifft

sinal = np.random.rand(10) + 1j * np.random.rand(10)

resultado = ifft(sinal)

print(sinal)
print(resultado)

[0.34742862+0.17900713j 0.45324876+0.38590859j 0.52882879+0.56501941j
 0.36035894+0.21418184j 0.92717978+0.496574j   0.21104036+0.13796775j
 0.84600741+0.12381062j 0.91288941+0.10550917j 0.10656706+0.11635231j
 0.02174183+0.68629616j]
[ 0.4715291 +0.3010627j  -0.16835852+0.06957874j  0.01494294+0.09362934j
  0.13123492+0.01729705j  0.00484806-0.14641743j  0.07967323-0.00491j
 -0.13895637-0.00218523j  0.0794824 -0.09553436j -0.07312924-0.08760195j
 -0.05383791+0.03408826j]


Exercıcios de SciPy 16

In [ ]:
from scipy.integrate import solve_ivp

def equacao(x, estado):
    y, v = estado
    return[v, -y]

solucao = solve_ivp(equacao, [0, 10], [1, 0])

print(solucao)

  message: The solver successfully reached the end of the integration interval.
  success: True
   status: 0
        t: [ 0.000e+00  9.990e-04 ...  9.429e+00  1.000e+01]
        y: [[ 1.000e+00  1.000e+00 ... -9.999e-01 -8.375e-01]
            [ 0.000e+00 -9.990e-04 ...  7.316e-03  5.461e-01]]
      sol: None
 t_events: None
 y_events: None
     nfev: 86
     njev: 0
      nlu: 0


Exercıcios de SciPy 17

In [ ]:
import numpy as np
from scipy import optimize

def f(x):
    return x**3 - 27

raiz = optimize.root(f, 2)

print(raiz.x)



[3.]


Exercıcios de SciPy 18

In [ ]:
import numpy as np
from scipy import interpolate

x = np.array([1, 2, 3, 4, 5])
y = x**2

f_interpolada = interpolate.interp1d(x, y, kind='cubic')
x_novo = np.array([1.5, 2.5, 3.5, 4.5])
y_novo = f_interpolada(x_novo)

print(y_novo)

[ 2.25  6.25 12.25 20.25]


Exercıcios de SciPy 19

In [ ]:
import numpy as np
from scipy.fft import fft

t = np.linspace(0, 1, 100)
sinal = np.sin(2 * np.pi * t) + np.cos(4 * np.pi * t)
frequencias = fft(sinal)

print(frequencias)

[ 1.00000000e+00-0.00000000e+00j  2.88605442e+00-4.96740864e+01j
  5.00765207e+01+3.83009663e+00j -8.60592286e-01+3.00531916e-01j
 -3.72704501e-01+2.25411249e-01j -2.24970566e-01+1.78417337e-01j
 -1.57493842e-01+1.47331108e-01j -1.20341090e-01+1.25279443e-01j
 -9.75003171e-02+1.08796674e-01j -8.23824167e-02+9.59830571e-02j
 -7.18280424e-02+8.57144954e-02j -6.41548686e-02+7.72838497e-02j
 -5.83953120e-02+7.02239780e-02j -5.39588521e-02+6.42137866e-02j
 -5.04676480e-02+5.90252153e-02j -4.76704164e-02+5.44917652e-02j
 -4.53945663e-02+5.04890019e-02j -4.35182707e-02+4.69220329e-02j
 -4.19534906e-02+4.37172107e-02j -4.06352911e-02+4.08164854e-02j
 -3.95149116e-02+3.81734687e-02j -3.85551516e-02+3.57506332e-02j
 -3.77272261e-02+3.35172818e-02j -3.70085777e-02+3.14480510e-02j
 -3.63813267e-02+2.95217911e-02j -3.58311536e-02+2.77207165e-02j
 -3.53464829e-02+2.60297532e-02j -3.49178766e-02+2.44360326e-02j
 -3.45375803e-02+2.29284931e-02j -3.41991770e-02+2.14975654e-02j
 -3.38973228e-02+2.013492

Exercıcios de SciPy 20

In [ ]:
import numpy as np
from scipy.linalg import solve

A = np.array([
    [1, 1, 1],
    [2, -1, 1],
    [1, 2, -1]
])

B = np.array([6, 3, 2])

resultado = solve(A, B)

print(resultado)

[1. 2. 3.]


Exercıcios de Pandas 1

In [1]:
import pandas as pd

dados = {
    "Produto": ["Tenis", "Meia", "Camisa", "Bermuda", "Bone"],
    "Preço": [500, 20, 150, 100, 90],
    "Quantidade": [5, 50, 7, 9, 6]
}

df = pd.DataFrame(dados)
print(df)

   Produto  Preço  Quantidade
0    Tenis    500           5
1     Meia     20          50
2   Camisa    150           7
3  Bermuda    100           9
4     Bone     90           6


Exercıcios de Pandas 2

In [2]:
import pandas as pd

planilha = pd.read_excel("vendas.xlsx")

print(planilha.head(10))

FileNotFoundError: [Errno 2] No such file or directory: 'vendas.xlsx'

Exercıcios de Pandas 3

In [4]:
import pandas as pd

tabela = {
    "Produto": ["Suco", "Agua", "Vinho"],
    "Preço": [8, 5, 150],
    "Quantidade": [50, 100, 20]
}

df = pd.DataFrame(tabela)
resultado = df[df["Preço"] > 100]
print(resultado)



  Produto  Preço  Quantidade
2   Vinho    150          20


Exercıcios de Pandas 4

In [6]:
import pandas as pd

tabela = {
    "Produto": ["Suco", "Agua", "Vinho"],
    "Preço": [8, 5, 150],
    "Quantidade": [50, 100, 20]
}

df = pd.DataFrame(tabela)
desconto = df["Preço"] * 0.1
df["Desconto"] = desconto
print(df)


  Produto  Preço  Quantidade  Desconto
0    Suco      8          50       0.8
1    Agua      5         100       0.5
2   Vinho    150          20      15.0


Exercıcios de Pandas 5

In [11]:
import pandas as pd

tabela = {
    "Produto": ["Suco", "Agua", "Vinho", "Whisky"],
    "Preço": [8, 5, 150, None],
    "Quantidade": [15, 100, 12, None]
}

df = pd.DataFrame(tabela)
remover = df.dropna()
print(remover)

  Produto  Preço  Quantidade
0    Suco    8.0        15.0
1    Agua    5.0       100.0
2   Vinho  150.0        12.0


Exercıcios de Pandas 6

In [12]:
import pandas as pd

tabela = {
    "Produto": ["Macarron", "Bolo", "Cupcake"],
    "Preço": [8, 15, 10],
    "Quantidade": [50, 20, 40]
}

df = pd.DataFrame(tabela)
ordem = df.sort_values(by = "Produto", ascending=True)
print(ordem)

    Produto  Preço  Quantidade
1      Bolo     15          20
2   Cupcake     10          40
0  Macarron      8          50


Exercıcios de Pandas 7

In [13]:
import pandas as pd

tabela = {
    "Produto": ["Macarron", "Bolo", "Cupcake"],
    "Preço": [8, 15, 10],
    "Quantidade": [50, 20, 40]
}

df = pd.DataFrame(tabela)
total = df["Preço"] * df["Quantidade"]
df["Total"] = total
print(df)

    Produto  Preço  Quantidade  Total
0  Macarron      8          50    400
1      Bolo     15          20    300
2   Cupcake     10          40    400


Exercıcios de Pandas 8

Exercıcios de Pandas 9

Exercıcios de Pandas 10

Exercıcios de Pandas 11

Exercıcios de Pandas 12

Exercıcios de Pandas 13

Exercıcios de Pandas 14

Exercıcios de Pandas 15

Exercıcios de Pandas 16

Exercıcios de Pandas 17

Exercıcios de Pandas 18

Exercıcios de Pandas 19

Exercıcios de Pandas 20